# Actuator health endpoint
management:
  endpoints:
    web:
      exposure:
        include: health

# Push metrics data to http://localhost:4318/v1/metrics for every 10 seconds
otlp:
  metrics:
    export:
      url: http://localhost:4318/v1/metrics
      step: 10s